

<div class="row">
<div class="col-lg-12">
	<h1>Edition de l'article <?php echo $post->getTitle() ?></h1>

	<?php 

		$form->setAttribute('action', $this->url('admin_edit_post', array('id' => $post->getId())))
		      ->prepare();

		echo $this->form()->openTag($form);

		echo $this->formHidden($form->get('csrf'));

		$fieldset = $form->get('post');

		echo $this->formRow($fieldset->get('title'))."<br>"."<br>";
		echo $this->formRow($fieldset->get('content'))."<br>"."<br>";
		echo $this->formRow($fieldset->get('category'))."<br>"."<br>";
		echo $this->formRow($fieldset->get('deleted'))."<br>"."<br>";
		if ($post->getPhoto()) {
			echo "<h4> Image actuelle</h4>"."<br>"."<br>";?>

		 	<img class="img-responsive" src="<?php echo $this->basePath($post->getWebPath()) ?>" style="height: 100px"; alt="<?php echo $post->getTitle() ?>">
			<br><br>
			<?php
		}
		else
			echo "<h4> Aucune photo pour le moment</h4>"."<br>"."<br>";

		echo $this->formRow($fieldset->get('file'))."<br>"."<br>";

		echo $this->formElement($form->get('submit'));
		echo $this->formElement($form->get('submit-and-continue'));

		echo "<a href=".$this->url('admin_list_post')." class='btn btn-default'>Annuler</a>";
		echo $this->form()->closeTag();

		?>
		
</div>

</div>
