
<h1>Edition de la catégorie <?php echo $post->getTitle() ?></h1>

<br>
<?php 

$form->setAttribute('action', $this->url('admin_edit_post', array('id' => $post->getId())))
      ->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('csrf'));

$post = $form->get('post');

echo $this->formRow($post->get('title'));
echo $this->formRow($post->get('content'));
echo $this->formRow($post->get('category'));
echo $this->formRow($post->get('deleted'));
echo $this->formRow($post->get('file'));

echo $this->formElement($form->get('submit'));
echo $this->formElement($form->get('submit-and-continue'));

echo $this->form()->closeTag();

?>
<a href="<?php echo $this->url('admin_list_post'); ?>" class="btn-xs">Annuler</a>