
<h1>Ajouter un nouvel article</h1>

<br>
<?php 

$form->setAttribute('action', $this->url('admin_new_post'))
      ->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('csrf'));

$post = $form->get('post');

echo $this->formRow($post->get('title'));
echo $this->formRow($post->get('content'));
echo $this->formRow($post->get('category'));
echo $this->formRow($post->get('deleted'));

echo $this->formElement($form->get('submit'));
echo $this->formElement($form->get('submit-and-continue'));

echo $this->form()->closeTag();