
<h1>Ajouter un nouvel article</h1>

<br>
<?php 
// $form->prepare();
$form->setAttribute('action', $this->url('admin_new_post'))
      ->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('csrf'));

$post = $form->get('post');

echo $this->formRow($post->get('title'))."<br>"."<br>";
echo $this->formRow($post->get('content'))."<br>"."<br>";
echo $this->formRow($post->get('category'))."<br>"."<br>";
echo $this->formRow($post->get('deleted'))."<br>"."<br>";
echo $this->formRow($post->get('file'))."<br>"."<br>";


echo $this->formElement($form->get('submit'));
echo $this->formElement($form->get('submit-and-continue'));

echo $this->form()->closeTag();