<section>
    <h2>Accueil administration</h2>
    <ul class="nav navbar-nav">
       
        <li><a class="mdl-navigation__link" href="<?php echo $this->url('admin_list_post') ?>"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">inbox</i>Articles</a></li>
        <li><a class="mdl-navigation__link" href="<?php echo $this->url('admin_list_category') ?>"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">report</i>Catégories</a></li>
        <li><a class="mdl-navigation__link" href="<?php echo $this->url('admin_list_comment') ?>"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">forum</i>Commentaires</a></li>
        <li><a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">people</i>Utilisateurs</a></li>
        <li><a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">delete</i>Poubelle</a></li>
        <li><a href="<?php echo $this->url('contact'); ?>">Contact</a></li>
        <li> <a class="mdl-navigation__link" href="<?php echo $this->url('zfcuser/logout') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>">Déconnexion</a></li>
      </ul>
</section>
