
  <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h1 class="page-header">
                Les derniers articles
            </h1>
            
            <?php foreach ($posts as $onePost): ?>
                <!-- First Blog Post -->
                <h2>
                    <a href="<?php echo $this->url('show_post',array('id' => $onePost->getId())); ?>"><?php echo $onePost->getTitle(); ?></a>
                </h2>
                <p class="lead">
                    écrit par <?php echo $onePost->getAuthor()->getUsername(); ?>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posté le <?php echo $onePost->getUpdatedAt()->format('l d F Y'); ?></p>
                <hr>
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                <hr>
                <p><?php echo substr($onePost->getContent(),0,100)."..."; ?></p>
                <a class="btn btn-primary" href="<?php echo $this->url('show_post',array('id' => $onePost->getId())); ?>">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
                <hr>
            <?php endforeach ?>
          
            <!-- Pager -->
        <!--     <ul class="pager">
                <li class="previous">
                    <a href="#">&larr; Older</a>
                </li>
                <li class="next">
                    <a href="#">Newer &rarr;</a>
                </li>
            </ul> -->

        </div>

        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Blog Search Well -->
            <div class="well">
                <h4>Blog Search</h4>
                <div class="input-group">
                    <input type="text" class="form-control">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-search"></span>
                    </button>
                    </span>
                </div>
                <!-- /.input-group -->
            </div>

            <!-- Blog Categories Well -->
            <div class="well">
                <h4>Blog Categories</h4>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled">
                      
                <?php foreach ($this->layout()->categorys as $oneCategory): ?>
                  <li><a href="<?php echo $this->url('show_category',array('slug' => $oneCategory->getSlug())); ?>"><?php echo $oneCategory->getLabel(); ?></a></li>
                <?php endforeach ?>
                        </ul>
                    </div>
                </div>
                <!-- /.row -->
            </div>

            <!-- Side Widget Well -->
            <!-- <div class="well">
                <h4>Side Widget Well</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
            </div> -->

        </div>

  </div>
