<?php 

  $flash = $this->flashMessenger();
  $flash->setMessageOpenFormat('<div%s>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
      &times;
  </button>
  <div>')->setMessageCloseString('</div></div>');

  echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
  echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
  echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
  echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

 ?>
 
<h1><?php echo $this->translate('Connexion'); ?></h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
        <a href="<?php echo $this->url('user_forgot_password'); ?>"> Mot de pass oublié?</a>
    </dl>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
<?php echo $this->translate('Not registered?'); ?> 
<!-- <a href="<?php //echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php //echo $this->translate('Sign up!'); ?></a> -->
<?php endif; ?>