<section>
    <h2>Home</h2>
    <div class="post">
        <p class="meta">
            <span class="date"><?php date("Y-m-d"); ?></span>
            <span class="posted">Posted by <a href="#">TEst</a></span>
        </p>
        <p class="meta">
            <span class="date"><?php date("Y-m-d"); ?></span>
            <span class="posted">Posted by <a href="#">TEst</a></span>
        </p>

        <p class="meta">
            <span class="date"><?php date("Y-m-d"); ?></span>
            <span class="posted">Posted by <a href="#">TEst</a></span>
        </p>
    </div>
</section>

<!-- <div class="row">


    <div style="clear: both;">&nbsp;</div>
</div> -->
