

<div class="row">
    <!-- Blog Post Content Column -->
    <div class="col-lg-8">
        <!-- Blog Post -->
        <!-- Title -->
        <h2><?php echo $post->getTitle(); ?></h2>
        <!-- Author -->
        <p class="lead">
            écrit par <?php echo $post->getAuthor()->getUsername(); ?>
        </p>
        <hr>
        <!-- Date/Time -->
        <p><span class="glyphicon glyphicon-time"></span> 
        Posté le <?php echo $this->dateFormat($post->getCreatedAt(), IntlDateFormatter::LONG, IntlDateFormatter::MEDIUM, "fr_FR"); ?></p>
        <hr>
        <!-- Preview Image -->
        <img class="img-responsive big-image" src="<?php echo $this->basePath($post->getWebPath()) ?>" alt="<?php echo $post->getTitle() ?>">
        
        <hr>
        <!-- Post Content -->
        <p class="lead"><?php echo $post->getContent(); ?></p>

        <hr>
        <!-- Blog Comments -->
        <!-- Comments Form -->
        <div class="well">
            <h4>Commenter:</h4>

            
            <?php 
            $form = $this->form;
            $form->setAttribute('action',
                                $this->url('show_post',array("id" => $post->getId())));

            $form->prepare();

            echo $this->form()->openTag($form);
            
            echo "<div id='img-captcha'>";
            echo $this->formRow($form->get('captcha'))."<br>"."<br>";
            echo "</div>";

            echo "<a id='refreshcaptcha' class='btn btn-info'>Rafraichir le captcha</a>"."<br>"."<br>";

            echo $this->formRow($form->get('comment'))."<br>"."<br>";
            echo $this->formRow($form->get('anonymous'))."<br>"."<br>";

            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();


             ?>
        </div>

        <hr>

        <!-- Posted Comments -->
        <?php if ($comments): ?>
            <?php foreach ($comments as $oneComment): ?>
                <div class="media">
                    <!-- <a class="pull-left" href="#"> -->
                        <?php //echo $oneComment->getAnonymous(); ?>
                    <!-- </a> -->
                    <div class="media-body">
                        <h4 class="media-heading"><?php echo $oneComment->getAnonymous(); ?>
                            <small><?php echo $this->dateFormat($oneComment->getCreatedAt(), IntlDateFormatter::LONG, IntlDateFormatter::MEDIUM, "fr_FR") ?></small>
                        </h4>
                        <?php echo $oneComment->getComment(); ?>
                    </div>
                </div>
                <hr>
            <?php endforeach ?>
            
        <?php else: ?>
            <h3>Soyez le premier à poster un commentaire</h3>
        <?php endif ?>

    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

        <!-- Blog Search Well -->
        <div class="well">
            <h4>Blog Search</h4>
            <div class="input-group">
                <input type="text" class="form-control">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <span class="glyphicon glyphicon-search"></span>
                </button>
                </span>
            </div>
            <!-- /.input-group -->
        </div>

        <!-- Blog Categories Well -->
        <div class="well">
                <h4>Blog Categories</h4>
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled">
                      
                <?php foreach ($this->layout()->categorys as $oneCategory): ?>
                  <li><a href="<?php echo $this->url('show_category',array('slug' => $oneCategory->getSlug())); ?>"><?php echo $oneCategory->getLabel(); ?></a></li>
                <?php endforeach ?>
                        </ul>
                    </div>
                </div>
                <!-- /.row -->
            </div>

        <!-- Side Widget Well -->
       <!--  <div class="well">
            <h4>Side Widget Well</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
        </div> -->

    </div>

</div>
<!-- /.row -->
<hr>
<!-- Footer -->
<!-- <footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Sport</p>
        </div>
    </div>
</footer> -->

</div>

<div id="spinner">
</div>

<script type="text/javascript">

    $(function(){
  
    config = [
     
    ] ;
    $('.ckeditor').ckeditor();

    $('#refreshcaptcha').click(function() {
        var url = '<?php echo $this->url("refresh_captcha_ajax", array("action"=>"refreshCaptchaAjax")) ?>';

        $.ajax({
            url: url, 
            dataType:'json', 
            beforeSend: function(xhr) {
                $("#spinner").show();
            },
            success: function(data) {
                $("#img-captcha").find('img').attr('src', data.src)
                $('input[type="hidden"][name="captcha[id]"').attr('value', data.id); 
                $('input[name="captcha[id]').focus(); 

            }
        })
        .done(function(data,textStatus) {
            if(textStatus == "success")
            {
                $("#spinner").hide();
            }
        })
        .fail(function() {
            $("#spinner").hide();
            alert("Le rechargement du captcha a échoué");
        });
        return false;
    });
});
</script>
