
<?php if($token->isValid()): ?>
<h1>Veuillez changer votre mot de passe</h1>
<?php 

$form->setAttribute('action', $this->url('user_change_password',array("token" => $token->getToken())))
      ->prepare();
$form = $this->form;

echo $this->form()->openTag($form);
echo $this->formRow($form->get('new_password')) . '<br />';
echo $this->formRow($form->get('confirm_new_password')) . '<br />';
echo $this->formRow($form->get('submit')->setLabel('Changer mon mot de passe'));
echo $this->formRow($form->get('csrf'));
echo $this->form()->closeTag($form);

?>


<?php else: ?>

<h1>Il semble que votre jeton a expiré</h1>
<br>
<a href="<?php echo $this->url("home"); ?>"> Retourner à l'accueil</a>

<?php endif; ?>