<!DOCTYPE html>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->

        <title>Sport Blog</title>

        <meta name="description" content="">
        <meta name="author" content="blog-sport">

    </head>

    <body class="">
		<p>Il semble que vous avez oublié votre mot de passe <br>
			<a href="<?php echo "http://".$host.$this->url("user_change_password",["token"=> $token]); ?>"> Mot de passse oublié ?</a>

			</p>

			<p>Vous avez un jour pour changer votre mot de passe.</p>
    </body>
</html>
