<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->

        <title>Sport Blog</title>

        <meta name="description" content="">
        <meta name="author" content="blog-sport">

    </head>

    <body class="">
		<?php echo $message; ?>
    </body>
</html>